{% set name = "layered-file-protocols" %}
{% set version = "0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/equinor/layered-file-protocols.git
  # NOTE: NO TAGS!!

build:
  number: 0

requirements:
  build:
    - git    
    - cmake
    - make   # [unix]
    - ninja  # [win]
    - {{ compiler('cxx') }}
    - fmtlib
  run:
    - fmtlib

about:
  home: https://github.com/equinor/layered-file-protocols.git
  summary: "Layered file protocols is a high-level interface for byte-oriented file handles with layering. File descriptors are composed and stacked at run-time, adding features such as pre-fetching, indices, cloud access, and file format support at each level."
  license: LGPL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bkreider
